### Создать и добавить вопрос c параметрами
POST http://localhost:8080/exam/java/add?question=testQuestion1&answer=testAnswer1

### Создать и добавить вопрос c параметрами
POST http://localhost:8080/exam/java/add?question=testQuestion2&answer=testAnswer2

### Создать и добавить вопрос c параметрами
POST http://localhost:8080/exam/java/add?question=testQuestion3&answer=testAnswer3

### Создать и добавть вопрос с телом запроса
POST http://localhost:8080/exam/java/add/question
Content-Type: application/json

{
  "question": "Test question #1",
  "answer": "Test answer to question #1"
}

### Удалить вопрос из хранилиища
GET http://localhost:8080/exam/java/remove?question=testQuestion1&answer=testAnswer1

### Запросить все вопросы из хранилища
GET http://localhost:8080/exam/java/

### Получить больше вопросов чем существует
GET http://localhost:8080/exam/getQuestions/8

### Получить несеолько вопросов из базы
GET http://localhost:8080/exam/getQuestions/2